package selenium.testcase;// Generated by Selenium IDE

import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.Test;
import selenium.pages.App;

import java.net.MalformedURLException;

public class TestWeWork {
    public static App app;

    @BeforeClass
    public static void beforeAll() throws MalformedURLException {
        app=new App();
        app.loginWithCookie();
        String phone="18501374810";
        app.toContact().delete(phone);
    }

    @Test
    public void testAdd() {
        String phone = "18501374810";
        app.toAddMember().add(phone, phone, phone);
        //assurtThat();
    }
    @Test
    public void delete(){
        String phone="18501374810";
        app.toAddMember().add(phone, phone, phone).delete(phone);
    }

    @Test
    public void deleteCurrentPage(){
        app.toContact().deleteCurrentPage();
    }

    @Test
    public void importFromFile(){
        app.toContact().importFromFile("C:/Users/yangxiaolong/Desktop/田猫科技通讯录.xlsx");
    }
    @AfterClass
    public static void afterAll() throws InterruptedException {
        app.quit();
    }
}