package selenium.testcase;// Generated by Selenium IDE

import org.junit.*;

import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import selenium.pages.App;

import java.util.*;
import java.util.concurrent.TimeUnit;

public class TestWeWork {
    public static App app;
    @BeforeClass
    public static void beforeAll(){
        app = new App();
        app.loginWithCookie();
        String phone = "18511866704";
        app.toContactPage().delete(phone);
    }

    @AfterClass
    public static void afterAll() throws InterruptedException {
        app.quit();
    }
    @Test
    public void testAdd(){
        String phone = "18511866704";
        app.toAddMember().add(phone,phone,phone);
        //assurtThat();
    }

    @Test
    public void delete(){
        String phone = "18511866703";
        app.toAddMember().add(phone,phone,phone).delete(phone);
    }
    @Test
    public void deleteCurrentPage(){
        app.toContactPage().deleteCurrentPage();
    }
}