package selenium.testcase;// Generated by Selenium IDE

import org.junit.BeforeClass;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import selenium.pages.App;

import java.util.*;
import java.util.concurrent.TimeUnit;

public class TestWeWork {
    public static App app;
    @BeforeClass
    public static void beforeAll(){
        app = new App();
        app.loginWithCookie();
    }
    @Test
    public void testStart(){
        String phone = "18501374811";
        app.toAddMember().add(phone,phone,phone);
        //assurtThat();
    }
}